version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: medical_exam_db
    environment:
      POSTGRES_USER: medexam
      POSTGRES_PASSWORD: medexam123
      POSTGRES_DB: medical_exam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15-alpine
    container_name: medical_exam_test_db
    environment:
      POSTGRES_USER: medexam
      POSTGRES_PASSWORD: medexam123
      POSTGRES_DB: medical_exam_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: medical_exam_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
